authentication:
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    client:
      id: "${IDENTITY_CLIENT_ID}"
      secret: "${IDENTITY_CLIENT_SECRET}"
    users:
      nodeA:
        clientId: "${NODE_A_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE
      nodeB:
        clientId: "${NODE_B_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE
      performance:
        clientId: "${PERFORMANCE_TEST_CLIENT_UID}"
        roles:
          - PIPE_READ
      nodeC:
        clientId: "${NODE_C_CLIENT_UID}"
        roles:
          - PIPE_READ
      admin:
        clientId: "${ADMIN_CLIENT_UID}"
        roles:
          - REGISTRY_DELETE
          - BOOTSTRAP_NODE
          - PIPE_READ

persistence:
  compact:
    schedule.cron: "0 14 0/1 * * ?"
  read:
    limit: 2500
    max-batch-size: 1000000
    retry-after: 120000
    expected-node-count: 30
    cluster-db-pool-size: 24
    read-delay-seconds: 60
    work-mem-mb: 512
