authentication:
  users:
    test:
      password: "${PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    pipe-runscope-test:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    test-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_TILL
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_TOKEN_PATH}"
    users:
      till:
        clientId: "${TILL_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

pipe:
  server:
    url: "${PIPE_URL}"
