authentication:
  users:
    pipe-provider-live:
      password: "${PIPE_READ_PASSWORD}"
    pipe-runscope-live:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    live-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_TILL
        - PIPE_READ
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_TOKEN_PATH}"
    users:
      till:
        clientId: "${TILL_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

pipe:
  server:
    url: "https://api.tesco.com/messaging/v1"
