authentication:
  users:
    pipe-provider-ppe:
      password: "${PIPE_READ_PASSWORD}"
    pipe-runscope-ppe:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    ppe-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_NODE
        - PIPE_READ
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_TOKEN_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    client:
      id: "${IDENTITY_CLIENT_ID}"
      secret: "${IDENTITY_CLIENT_SECRET}"
    users:
      nodeA:
        clientId: "${NODE_A_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE
      nodeB:
        clientId: "${NODE_B_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

location:
  url: "${LOCATION_URL}"

pipe:
  server:
    url: "https://api-ppe.tesco.com/messaging/v1"
