authentication:
  users:
    pipe-provider-live:
      password: "${PIPE_READ_PASSWORD}"
    pipe-runscope-live:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    live-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_NODE
        - PIPE_READ
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    client:
      id: "${IDENTITY_CLIENT_ID}"
      secret: "${IDENTITY_CLIENT_SECRET}"
    users:
      nodeA:
        clientId: "${NODE_A_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE
      nodeB:
        clientId: "${NODE_B_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

location:
  url: "${LOCATION_URL}"

pipe:
  server:
    url: "${PIPE_URL}"

persistence:
  compact:
    schedule.cron: "0 14 0/1 1/1 * ? *"
  read:
    limit: 2500
    max-batch-size: 1000000
    retry-after: 240000
    expected-node-count: 7000
    cluster-db-pool-size: 24
    read-delay-seconds: 60
    work-mem-mb: 512
