authentication:
  users:
    test:
      password: "${PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    pipe-runscope-test:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    test-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_NODE
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    client:
      id: "${IDENTITY_CLIENT_ID}"
      secret: "${IDENTITY_CLIENT_SECRET}"
    users:
      nodeA:
        clientId: "${NODE_A_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

location:
  url: "${LOCATION_URL}"

pipe:
  server:
    url: "${PIPE_URL}"

persistence:
  compact:
    threshold: 3d
    schedule.cron: "0 14 2 1/1 * ?"
  read:
    limit: 20000
    max-batch-size: 2000000
    retry-after: 1
    expected-node-count: 3
    cluster-db-pool-size: 72
    read-delay-seconds: 1