authentication:
  users:
    pipe-provider-ppe:
      password: "${PIPE_READ_PASSWORD}"
    pipe-runscope-ppe:
      password: "${RUNSCOPE_PIPE_READ_PASSWORD}"
      roles:
        - PIPE_READ
    ppe-support:
      password: "${SUPPORT_PASSWORD}"
      roles:
        - REGISTRY_DELETE
        - BOOTSTRAP_TILL
        - PIPE_READ
  identity:
    url: "${IDENTITY_URL}"
    validate.token.path: "${IDENTITY_VALIDATE_TOKEN_PATH}"
    issue.token.path: "${IDENTITY_ISSUE_TOKEN_PATH}"
    client:
      id: "someClientId"
      secret: "someClientSecret"
    users:
      till:
        clientId: "${TILL_CLIENT_UID}"
        roles:
          - PIPE_READ
          - REGISTRY_WRITE

micronaut:
  http:
    services:
      identity-issue-token:
        url: "${IDENTITY_URL}"
        logger-name: issue.token.client

pipe:
  server:
    url: "https://api-ppe.tesco.com/messaging/v1"
