apiVersion: v1
kind: Service
metadata:
  namespace: app-aqueduct-pipe
  name: aqueduct-pipe
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: aqueduct-pipe
