micronaut:
  metrics.binders:
    jvm.enabled: true
    web.enabled: true
    processor.enabled: true
    jdbc.enabled: false
  security:
    enabled: true
    token.jwt:
      enabled: true
      bearer.enabled: true
  caches:
    identity-cache:
      expire-after-write: 10m
    cluster-cache:
      expire-after-write: 1h
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  all:
    enabled: true
    path: /endpoints
    sensitive: false

persistence:
  compact:
    threshold: 3d
    schedule.cron: "0 14 2 1/1 * ?"
  read:
    limit: 1000
    max-batch-size: 2000000
    retry-after: 10

datasources:
  postgres:
    url: "jdbc:postgresql://${POSTGRE_SERVER}/${POSTGRE_DATABASE}"
    username: "${POSTGRE_USERNAME}"
    password: "${POSTGRE_PASSWORD}"
    driverClassName: org.postgresql.Driver

authentication:
  identity:
    delay: 500ms
    attempts: 3
